server:
  port: 1227
  servlet:
    context-path: /gbo

spring:
  profiles:
    active: prod #对应不同的环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.yangshuqian.com:3306/shuqian_db
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
  thymeleaf:
      prefix: classpath:/templates/  #指定模板所在的目录
      check-template-location: true  #检查模板路径是否存在
      cache: false #是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      servlet:
        content-type: text/html
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  messages:
    encoding: UTF-8
    basename: messages

logging:
  config: classpath:log4j2-log.xml
